name: environment workflow
run-name: env workflow

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: environment
        default: Development

jobs:
  env-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}
    steps:
      - name: fetching the environment
        run: |
          echo "${{ vars.UNAME }}"
          echo "${{ secrets.ENVDEV }}"
