name: Job Context Demo
run-name: Job Context Demo

on: 
  push:

jobs:
  job1:
   runs-on: ubuntu-latest  
   env:
    job_name: job1
    
   steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Job Context
        run: |
          echo "Job name: ${{ env.job_name }}"
          echo "Job Status: ${{ job.status }}"
    
      - name: Print GitHub Context
        run: |   
          echo "Repository Name: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
      - name: Print Runner Context
        run: |
          echo "Runner Context:"
          echo "OS: ${{ runner.os }}"
          echo "Architecture: ${{ runner.arch }}"

      

  job2:
    needs: job1  # Job 2 depends on Job 1 (can use its outputs)
    runs-on: ubuntu-latest
    env:
     job_name: job2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Access Output from Job 1
        run: |
          echo "Output from Job 1: ${{ env.output_value }}"

      - name: Print Job Context
        run: |
          echo "Job Name: ${{ env.job_name }}"
          echo "Job Status: ${{ job.status }}"
          
      - name: Print Event Context
        run: |
          echo "Event Context:"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
