name: Node.js Application Workflow on mac runner (self hosted)
run-name: node.js on MAC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: mac-runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # This step checks out the repository to the runner.

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify Node.js version (can be 14, 16, etc.)
        # This step sets up the specified version of Node.js.

      - name: Install dependencies
        run: |
          npm install
        # This step installs the project dependencies.

      - name: Run tests
        run: |
          npm test
        # This step runs the tests for the project.

      - name: Build the application
        run: |
          mkdir build
          # Simulating a build process (in this case just creating an artifact)
          echo "Build artifacts for the Node.js app" > build/artifact.txt
          echo "Node.js Application Build" >> build/artifact.txt
        # This step builds the application and creates a build artifact.

      - name: Store build artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: node-app-artifact
          path: build/
        # This step uploads the build artifact.
