name: Test Node.js App

on:
  workflow_call:  # Defines this workflow as reusable
    inputs:
      node_version:
        required: true
        type: string
        description: "Node.js version to use."

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out the repository to the runner.
        
      - name: Set up Node.js
        uses: actions/setup-node@v3  # This step sets up the specified version of Node.js.
        with:
          node-version: ${{ inputs.node_version }}
      
      - name: Install dependencies
        run: npm install  # This step installs the project dependencies.
      
      - name: Run tests
        run: npm test  # This step runs the tests for the project.
