name: Example Using Environment Variables and Outputs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VAR: "Hello from the env context"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message using env variable
        run: |
          echo "This is a message: ${{ env.MY_VAR }}"

  
