name: Example vars
run-name: vars demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VAR: "Hello from the env context"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message using env variable
        run: |
          echo "This is from repo ${{ vars.UNAME }}"
          echo " This is from local worflow ${{ vars.MY_VAR" }}"
        

  
