name: Example vars
run-name: vars demo

on: 
 push:
# env:
  # MY_VAR: "Hello from the env context"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message using env variable
        run: |
          echo "This is from repo ${{ vars.myvar }}"
          # echo " This is from local worflow ${{ vars.MY_VAR" }}"
        

  
