name: Example Workflow with Context

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: mac-runner

    steps:
    
    - name: Display GitHub context
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "SHA: ${{ github.sha }}"
        echo "Event: ${{ github.event_name }}"
      
